TIMETABLE_MANAGEMENT_SYSTEM/Models/ErrorViewModel.cs
using System;

namespace TIMETABLE_MANAGEMENT_SYSTEM.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TIMETABLE_MANAGEMENT_SYSTEM/Models/TimeTableModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TIMETABLE_MANAGEMENT_SYSTEM.Models
{
    public class TimeTableModel
    {
        public int ID { get; set; } = 0;
        public int BRANCH_ID { get; set; } = 0;
        public int DEPT_ID { get; set; } = 0;
        public int SEMISTER_ID { get; set; } = 0;
        public string SEMISTER_NAME { get; set; } = null;
        public string DAY { get; set; } = null;
        public int YEAR_OF_EDUCATION { get; set; } = 0;
        public string TEACHER_NAME { get; set; } = null;
        public string SUBJECT_NAME { get; set; } = null;
        public string FROMTIME { get; set; } = null;
        public string TOTIME { get; set; } = null;
        public string TOTALTIME { get; set; } = null;
        public List<Time> listPeriod { get; set; }
        public string XMLNODE { get; set; } = null;
        public int NO_OF_YEAR { get; set; } = 0;
        public int PMSG_OUT { get; set; } = 0;
        public string DEPT_NAME { get; set; } = null;
        public string BRANCH_NAME { get; set; } = null;
    }
    public class Time
    {
        public string PERIODS { get; set; } = null;
        public string TEACHER_NAME { get; set; } = null;
        public string SUBJECT_NAME { get; set; } = null;
        public string FROMTIME { get; set; } = null;
        public string TOTIME { get; set; } = null;
        public string TOTALTIME { get; set; } = null;
    }
}

TIMETABLE_MANAGEMENT_SYSTEM/Controllers/TimeTableController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using TIMETABLE_MANAGEMENT_SYSTEM.Models;
using TIMETABLE_MANAGEMENT_SYSTEM.Services;

namespace TIMETABLE_MANAGEMENT_SYSTEM.Controllers
{
    public class TimeTableController : Controller
    {
        private readonly ITIMETABLE_SERVICE _timetable;
        public TimeTableController(ITIMETABLE_SERVICE timetable)
        {
            _timetable = timetable;
        }
        public async Task<IActionResult> Add()
        {
            List<TimeTableModel> lstDepartment = new List<TimeTableModel>();
            int DEPT_ID = 0;
            lstDepartment = await _timetable.Bind_DepartmentService(DEPT_ID);
            lstDepartment.Insert(0, new TimeTableModel { DEPT_ID = 0, DEPT_NAME = "Please Select Department" });
            ViewBag.Department = lstDepartment;
            return View();
        }
        public async Task<JsonResult> Branch_Bind(int DEPT_ID)
        {
            var subcatList = await _timetable.Bind_BranchService(DEPT_ID);
            List<SelectListItem> scalist = new List<SelectListItem>();
            foreach (TimeTableModel dr in subcatList)
            {
                scalist.Add(new SelectListItem { Text = dr.BRANCH_NAME, Value = dr.BRANCH_ID.ToString() });
            }
            var jsonres = JsonConvert.SerializeObject(scalist);
            return Json(jsonres);
        }
        public async Task<JsonResult> Semister_Bind(int NO_OF_YEAR)
        {
            var subcatList = await _timetable.Bind_SemisterService(NO_OF_YEAR);
            List<SelectListItem> scalist = new List<SelectListItem>();
            foreach (TimeTableModel dr in subcatList)
            {
                scalist.Add(new SelectListItem { Text = dr.SEMISTER_NAME, Value = dr.SEMISTER_ID .ToString() });
            }
            var jsonres = JsonConvert.SerializeObject(scalist);
            return Json(jsonres);
        }
        public async Task<JsonResult> Year_Bind(int DEPT_ID)
        {
            var subcatList = await _timetable.Bind_DepartmentService(DEPT_ID);
            var jsonres = JsonConvert.SerializeObject(subcatList);
            return Json(jsonres);
        }
        [HttpPost]
        public async Task<JsonResult> SaveUpdate(TimeTableModel se)
        {
            if (se.listPeriod != null)
            {
                se.XMLNODE = ConvertDtToXml(se.listPeriod);
                int data = await _timetable.InsertService(se);
                return Json(data);
            }
            else
            {
                return Json(4);
            }
        }
        private string ConvertDtToXml<T>(List<T> items)
        {
            DataTable dt = ToDataTable(items);
            dt.TableName = "Timetable";
            System.IO.StringWriter stringWriter = new StringWriter();
            dt.WriteXml(stringWriter);
            string xmlFormat = stringWriter.ToString();
            return xmlFormat;
        }
        public static DataTable ToDataTable<T>(List<T> items)
        {
            DataTable dataTable = new DataTable(typeof(T).Name);

            //Get all the properties
            PropertyInfo[] Props = typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance);
            foreach (PropertyInfo prop in Props)
            {
                //Defining type of data column gives proper data table 
                var type = (prop.PropertyType.IsGenericType && prop.PropertyType.GetGenericTypeDefinition() == typeof(Nullable<>) ? Nullable.GetUnderlyingType(prop.PropertyType) : prop.PropertyType);
                //Setting column names as Property names
                dataTable.Columns.Add(prop.Name, type);
            }
            foreach (T item in items)
            {
                var values = new object[Props.Length];
                for (int i = 0; i < Props.Length; i++)
                {
                    //inserting property values to datatable rows
                    values[i] = Props[i].GetValue(item, null);
                }
                dataTable.Rows.Add(values);
            }
            //put a breakpoint here and check datatable
            return dataTable;
        }
    }
}

TIMETABLE_MANAGEMENT_SYSTEM/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TIMETABLE_MANAGEMENT_SYSTEM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TIMETABLE_MANAGEMENT_SYSTEM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TimeTable" asp-action="Add">Add</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TimeTable" asp-action="View">View</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TIMETABLE_MANAGEMENT_SYSTEM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TIMETABLE_MANAGEMENT_SYSTEM/Views/TimeTable/Add.cshtml
@{
    ViewData["Title"] = "Add";
}

<div class="row">
    <div class="form-group col-md-4">
        <label for="DEPT_ID">Department</label><span style="color:red;">*</span>
        <select asp="DEPT_ID" id="DEPT_ID" asp-items="@(new SelectList( ViewBag.Department,"DEPT_ID","DEPT_NAME"))" class="form-control">
        </select>
        <label id="year" style="float:right"></label>
    </div>
    <div class="form-group col-md-4" id="divBranch">
        <label for="BRANCH_NAME">Branch</label><span style="color:red;">*</span>
        <select asp="BRANCH_ID" id="BRANCH_ID" class="form-control">
        </select>
    </div>
    <div class="form-group col-md-4">
        <label for="SEMISTER_ID">Semester</label><span style="color:red;">*</span>
        <select asp="SEMISTER_ID" id="SEMISTER_ID" class="form-control">
        </select>
    </div>
</div>

<div class="row">
    <div class="form-group col-md-4">
        <label for="DAY">Day</label><span style="color:red;">*</span>
        <select asp="DAY" id="DAY" class="form-control">
            <option value="0">Please Select Day</option>
            <option value="1">MON</option>
            <option value="2">TUE</option>
            <option value="3">WED</option>
            <option value="4">THU</option>
            <option value="5">FRI</option>
            <option value="6">SAT</option>
        </select>
    </div>
    <div class="form-group col-md-4">
        <label for="TEACHER_NAME">Teacher Asign</label><span style="color:red;">*</span>
        <input type="text" id="TEACHER_NAME" class="form-control" placeholder="Enter Teacher Name" />
        <span style="color:red;"></span>
    </div>
    <div class="form-group col-md-4">
        <label for="SUBJECT_NAME">Subject</label><span style="color:red;">*</span>
        <input type="text" id="SUBJECT_NAME" class="form-control" placeholder="Enter Subject Name" />
        <span style="color:red;"></span>
    </div>
</div>
<div class="row">
    <div class="form-group col-md-4">
        <label for="period">Period</label><span style="color:red;">*</span>
        <select asp="period" id="period" class="form-control">
            <option value="0">Please Select Period</option>
            <option value="1">1ST-PERIOD</option>
            <option value="2">2ND-PERIOD</option>
            <option value="3">3RD-PERIOD</option>
            <option value="4">4TH-PERIOD</option>
            <option value="5">5TH-PERIOD</option>
            <option value="6">6TH-PERIOD</option>
            <option value="7">7TH-PERIOD</option>
        </select>
    </div>
    <div class="form-group col-md-4">
        <label for="from">From</label><span style="color:red;">*</span>
        <input type="time" id="from" class="form-control" />
        <span style="color:red;"></span>
    </div>
    <div class="form-group col-md-4">
        <label for="to">To</label><span style="color:red;">*</span>
        <input type="time" id="to" class="form-control" />
        <span style="color:red;"></span>
    </div>
</div>
<div class="row">
    <div class="form-group col-md-4"></div>
    <div class="form-group col-md-4"></div>
    <div class="form-group col-md-4">
        <input type="button" id="btnAdd" value="Add" class="btn btn-primary" style="float:right" />
    </div>
</div>
<div class="table row text-center" id="divTable">
    <table id="timePeriod" align="center">
        <thead>
            <tr>
                <th>Period(Which Period ?)</th>
                <th>Subject</th>
                <th>Teacher Assign</th>
                <th>Time Taken</th>
                <th>Total Time</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-sm-12 text-center mt-3 form-group">
        <input type="button" id="saveupdate" value="Submit" class="btn btn-primary" />
        <input type="button" id="btnreset" value="Reset" class="btn btn-danger" />
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    function Validation() {

        if ($('#DEPT_ID').val() == 0) {
            alert("Please Select Department")
            $('#DEPT_ID').focus();
            return false;
        }
        else if ($('#DEPT_ID').text() == "B.TECH") {
            if ($('#BRANCH_ID').val() == 0) {
                alert("Please Select Branch")
                $('#BRANCH_ID').focus();
                return false;
            }
            return false;
        }
        else if ($('#SEMISTER_ID').val() == 0) {
            alert("Please Select Semister")
            $('#SEMISTER_ID').focus();
            return false;
        }
        else if ($('#DAY').val() == 0) {
            alert("Please Select Day")
            $('#DAY').focus();
            return false;
        }
        else if ($('#timePeriod tbody tr').length <= 0) {
            alert('Please Add Periods First');
            return false;
        }
        else {
            return true;
        }
    }

    function Validate() {
        if ($('#TEACHER_NAME').val() == "") {
            alert("Please Enter Teacher's Name")
            $('#TEACHER_NAME').focus();
            return false;
        }
        else if ($('#SUBJECT_NAME').val() == "") {
            alert("Please Enter Subject Name")
            $('#SUBJECT_NAME').focus();
            return false;
        }
        else if ($('#period').val() == 0) {
            alert("Please Select Period")
            $('#period').focus();
            return false;
        }
        else if ($('#from').val() == "") {
            alert("Please Enter From Time")
            $('#DAY').focus();
            return false;
        }
        else if ($('#to').val() == "") {
            alert('Please Enter To Time');
            return false;
        }
        else {
            return true;
        }
    }
    $(window).on("load", function () {
        $("#divBranch").hide();
        $("#divTable").hide();
    });

    $(document).ready(function () {
        $("#DEPT_ID").change(function () {

            var id = $(this).val();
            $("#year").empty();
            $.getJSON("/TimeTable/Year_Bind", { DEPT_ID: id }, function (data) {
                prod = JSON.parse(data);

                var noofyear = prod[0].NO_OF_YEAR
                $("#year").text(`(` + noofyear + ` Years)`);


                $("#SEMISTER_ID").empty();
                $.getJSON("/TimeTable/Semister_Bind", { NO_OF_YEAR: noofyear }, function (data) {
                    data = JSON.parse(data);
                    var v = "<option value=0>Please Select Semister</option>";
                    $.each(data, function (i, v1) {
                        v += "<option value=" + v1.Value + ">" + v1.Text + "</option>";
                    });
                    $("#SEMISTER_ID").html(v);
                });
            });

            if ($('#DEPT_ID option:selected').text() == "B.TECH") {
                $('#divBranch').show();
                $("#BRANCH_ID").empty();

                $.getJSON("/TimeTable/Branch_Bind", { DEPT_ID: id }, function (data) {
                    data = JSON.parse(data);
                    var v = "<option value=0>Please Select Branch</option>";
                    $.each(data, function (i, v1) {
                        v += "<option value=" + v1.Value + ">" + v1.Text + "</option>";
                    });
                    $("#BRANCH_ID").html(v);
                });
            }
            else {
                $('#divBranch').hide();
            }


        });
    })

    $("#saveupdate").click(function () {
        if (Validation()) {
            debugger
            var Items = []; //array declaring to store the records to send it to controller
            var entity = {};
            var tbl = document.getElementById('timePeriod');
            for (var i = 1; i < tbl.rows.length; i++) {
                var item1 = {};
                item1.PERIODS = tbl.rows[i].children[0].textContent;
                item1.SUBJECT_NAME = tbl.rows[i].children[1].textContent;
                item1.TEACHER_NAME = tbl.rows[i].children[2].textContent;
                item1.FROMTIME = tbl.rows[i].children[3].textContent;
                item1.TOTALTIME = tbl.rows[i].children[4].textContent;
                //item1.TOTALTIME = tbl.rows[i].children[5].textContent;
                Items.push(item1);
            }
            entity.DEPT_ID = $("#DEPT_ID").val();
            entity.BRANCH_ID = $("#BRANCH_ID").val();
            entity.SEMISTER_ID = $("#SEMISTER_ID").val();
            entity.SEMISTER_NAME = $('#SEMISTER_ID option:selected').text();
            entity.DAY = $('#DAY option:selected').text();
            var y = $("#year").text();
            var year = y.substring(1,2);
            entity.YEAR_OF_EDUCATION = year;
            entity.listPeriod = Items;

            $.ajax({
                url: "/TimeTable/SaveUpdate",
                data: entity,
                type: "POST",
                success: function (result) {
                    
                },
                error: function (errormessage) {
                    alert("error");
                }
            });
        };
    });

    $("#btnAdd").click(function () {
        if (Validate()) {
            $("#divTable").show();
            var teacher = $('#TEACHER_NAME').val();
            var subject = $('#SUBJECT_NAME').val();
            var timeperiod = $('#period option:selected').text();
            var fromtime = $('#from').val();
            var totime = $('#to').val();
            s = fromtime.split(':');
            e = totime.split(':');
            min = e[1] - s[1];
            hour_carry = 0;
            if (min < 0) {
                min += 60;
                hour_carry += 1;
            }
            hour = e[0] - s[0] - hour_carry;
            if (hour == "0") {
                diff = min + "min";
            }
            else if (min == "0") {
                diff = hour + "hr";
            }
            else {
                diff = hour + ":" + min;
            }

            //$("#timePeriod tbody").append(
            //    `<tr><td>` + timeperiod + `</td><td>` + subject + `</td><td>` + teacher + `</td><td>` + fromtime + `-` + totime + `</td><td>` + diff + `</td></tr>`
            //);


            var rowcount = $("#timePeriod tbody tr").length;
            var colcount = $("#timePeriod tbody tr td").length;
            var i

            if (rowcount != 0) {
                for (i = 0; i < rowcount; i++) {
                    var row = $("#timePeriod tbody").find("tr").eq(i).html();
                   
                    var item1 = [];
                    var tbl = document.getElementById('timePeriod');
                    for (var i = 0; i < tbl.rows.length; i++) {
                        item1.push(tbl.rows[i].children[0].textContent)
                    }
                    
                    var skillsSelect = document.getElementById("period");
                    var selectedText = skillsSelect.options[skillsSelect.selectedIndex].text;


                    if (item1.includes(selectedText)) {
                        alert(selectedText + " is Already Added");
                        return;
                    }
                    else {
                        $("#timePeriod tbody").append(
                            `<tr><td>` + timeperiod + `</td><td>` + subject + `</td><td>` + teacher + `</td><td>` + fromtime + `-` + totime + `</td><td>` + diff + `</td></tr>`
                        );
                    }
                    
                }
            }
            else {
                $("#timePeriod tbody").append(
                    `<tr><td>` + timeperiod + `</td><td>` + subject + `</td><td>` + teacher + `</td><td>` + fromtime + `-` + totime + `</td><td>` + diff + `</td></tr>`
                );
            }
        };
    });
</script>